### ISSUE TITLE
Compatibility with `undetected-chromedriver`

### ISSUE THREAD

**Issue by Benjamin-Loison** [Benjamin-Loison/selenium-wire#5]
[undetected-chromedriver](https://github.com/ultrafunkamsterdam/undetected-chromedriver)

**Comment by Benjamin-Loison** [comment]
Would help [Online_authentication_API/issues/73](https://codeberg.org/Benjamin_Loison/Online_authentication_API/issues/73) and [Webscrap_any_website/issues/51](https://codeberg.org/Benjamin_Loison/Webscrap_any_website/issues/51).

**Comment by Benjamin-Loison** [comment]
<details>
<summary>Python script:</summary>

```python
import seleniumwire.undetected_chromedriver as webdriver
from selenium.webdriver.chrome.options import Options

options = Options()

options.add_argument('--proxy-server=socks5://localhost:9999')

driver = webdriver.Chrome(options)
```
</details>
<details>
<summary>Output:</summary>

```
Traceback (most recent call last):
  File "<tmp 2>", line 12, in <module>
    driver = webdriver.Chrome(options)
  File "/home/benjamin/venv/lib/python3.12/site-packages/seleniumwire/undetected_chromedriver/webdriver.py", line 61, in __init__
    super().__init__(*args, **kwargs)
TypeError: Chrome.__init__() got multiple values for argument 'options'
```
</details>

Source: [wkeeling/selenium-wire/issues/735](https://github.com/wkeeling/selenium-wire/issues/735)

**Comment by Benjamin-Loison** [comment]
```python
from seleniumwire.webdriver.chrome.options import Options
```
<details>
<summary>Output:</summary>

```
Traceback (most recent call last):
  File "<tmp 4>", line 2, in <module>
    from seleniumwire.webdriver.chrome.options import Options
ModuleNotFoundError: No module named 'seleniumwire.webdriver.chrome'; 'seleniumwire.webdriver' is not a package
```
</details>

**Comment by Benjamin-Loison** [comment]
DuckDuckGo and Google `"seleniumwire.undetected_chromedriver" options`.

**Comment by Benjamin-Loison** [comment]
```python
options = webdriver.Options()
```
<details>
<summary>Output:</summary>

```
Traceback (most recent call last):
  File "<tmp 4>", line 3, in <module>
    options = webdriver.Options()
AttributeError: module 'seleniumwire.undetected_chromedriver' has no attribute 'Options'
```
</details>

**Comment by Benjamin-Loison** [comment]
```python
options = webdriver.ChromeOptions()
```
<details>
<summary>Output:</summary>

```
Traceback (most recent call last):
  File "<tmp 4>", line 7, in <module>
    driver = webdriver.Chrome(options)
  File "/home/benjamin/venv/lib/python3.12/site-packages/seleniumwire/undetected_chromedriver/webdriver.py", line 61, in __init__
    super().__init__(*args, **kwargs)
TypeError: Chrome.__init__() got multiple values for argument 'options'
```
</details>

**Comment by Benjamin-Loison** [comment]
```python
help(webdriver.Chrome)
```
<details>
<summary>Output:</summary>

```
Help on class Chrome in module seleniumwire.undetected_chromedriver.webdriver:

class Chrome(seleniumwire.inspect.InspectRequestsMixin, seleniumwire.webdriver.DriverCommonMixin, undetected_chromedriver.Chrome)
 |  Chrome(*args, seleniumwire_options=None, **kwargs)
 |
 |  Extends the undetected_chrome Chrome webdriver to provide additional
 |  methods for inspecting requests.
 |
 |  Method resolution order:
 |      Chrome
 |      seleniumwire.inspect.InspectRequestsMixin
 |      seleniumwire.webdriver.DriverCommonMixin
 |      undetected_chromedriver.Chrome
 |      selenium.webdriver.chrome.webdriver.WebDriver
 |      selenium.webdriver.chromium.webdriver.ChromiumDriver
 |      selenium.webdriver.remote.webdriver.WebDriver
 |      selenium.webdriver.remote.webdriver.BaseWebDriver
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __init__(self, *args, seleniumwire_options=None, **kwargs)
 |      Initialise a new Chrome WebDriver instance.
 |
 |      Args:
 |          seleniumwire_options: The seleniumwire options dictionary.
```
</details>

**Comment by Benjamin-Loison** [comment]
Same error with `seleniumwire.undetected_chromedriver.v2`.

**Comment by Benjamin-Loison** [comment]
DuckDuckGo and Google `"Chrome.__init__() got multiple values for argument 'options'"` do not return any result.

**Comment by Benjamin-Loison** [comment]
DuckDuckGo `"seleniumwire.undetected_chromedriver" "add_argument"`.

**Comment by Benjamin-Loison** [comment]
![image](https://github.com/user-attachments/assets/43a23260-e23d-432d-897b-8b006e4be38d)

![image](https://github.com/user-attachments/assets/59f15bb9-3e53-48a6-9f38-fb40807de540)

<details>
<summary><code>--proxy-server</code> does not seem taken into account in:</summary>

```python
import seleniumwire.undetected_chromedriver as webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options

options = webdriver.ChromeOptions()

#options.add_argument('-headless')
#options.add_argument('--proxy-server=socks5://localhost:9999')

driver = webdriver.Chrome(options = options)

driver.get('https://ifconfig.me')
print(driver.find_element(By.ID, 'ip_address').get_attribute('innerHTML'))

driver.close()
```
</details>

**Comment by Benjamin-Loison** [comment]
DuckDuckGo `"Your connection is not private" "seleniumwire.undetected_chromedriver"`.

```bash
python3 -m seleniumwire extractcert
```
```
ca.crt extracted. You can now import this into a browser.
```

```bash
ls -l ca.crt
```
```
-rw-rw-r-- 1 benjamin benjamin 1826 Oct 27 17:43 ca.crt
```

**Comment by Benjamin-Loison** [comment]
```bash
sudo apt install -y libnss3-tools
```
<details>
<summary>Output:</summary>

```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  libnss3-tools
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 615 kB of archives.
After this operation, 2,193 kB of additional disk space will be used.
Get:1 http://mirrors.ircam.fr/pub/ubuntu/archive noble/main amd64 libnss3-tools amd64 2:3.98-1build1 [615 kB]
Fetched 615 kB in 1s (438 kB/s)        
Selecting previously unselected package libnss3-tools.
(Reading database ... 961154 files and directories currently installed.)
Preparing to unpack .../libnss3-tools_2%3a3.98-1build1_amd64.deb ...
Unpacking libnss3-tools (2:3.98-1build1) ...
Setting up libnss3-tools (2:3.98-1build1) ...
Processing triggers for man-db (2.12.0-4build2) ...
```
</details>

Related to [Benjamin-Loison/selenium/issues/11](https://github.com/Benjamin-Loison/selenium/issues/11).

**Comment by Benjamin-Loison** [comment]
```bash
certutil -d sql:$HOME/.pki/nssdb -A -t TC -n 'Selenium Wire' -i ca.crt
```

does not return anything.

**Comment by Benjamin-Loison** [comment]
DuckDuckGo `"socks5" "seleniumwire.undetected_chromedriver"`.

**Comment by Benjamin-Loison** [comment]
<details>
<summary>Python script:</summary>

```python
import seleniumwire.undetected_chromedriver as webdriver
from selenium.webdriver.common.by import By

options = webdriver.ChromeOptions()

options.add_argument('-headless')

seleniumwireOptions = {
    'proxy': {
        'https': 'socks5://localhost:9999',
    }
}

driver = webdriver.Chrome(seleniumwire_options = seleniumwireOptions, options = options)

driver.get('https://ifconfig.me')
print(driver.find_element(By.ID, 'ip_address').get_attribute('innerHTML'))

driver.close()
```
</details>

Source: https://scrapfly.io/blog/how-to-intercept-background-requests-with-selenium-wire/

works as wanted.

Note that precising `seleniumwire_options = ` is mandatory otherwise face the same issue as before.

**Comment by Benjamin-Loison** [comment]
[wkeeling/selenium-wire/issues/207](https://github.com/wkeeling/selenium-wire/issues/207)

**Comment by Benjamin-Loison** [comment]
[wkeeling/selenium-wire/blob/da1b675fe2cc6dae2e3bb959c1ce95eb1c41830b/README.rst#certificates](https://github.com/wkeeling/selenium-wire/blob/da1b675fe2cc6dae2e3bb959c1ce95eb1c41830b/README.rst#certificates)

**Comment by Benjamin-Loison** [comment]
[wkeeling/selenium-wire/blob/da1b675fe2cc6dae2e3bb959c1ce95eb1c41830b/README.rst#bot-detection](https://github.com/wkeeling/selenium-wire/blob/da1b675fe2cc6dae2e3bb959c1ce95eb1c41830b/README.rst#bot-detection)

**Comment by Benjamin-Loison** [comment]
Or undetected geckodriver.

**Comment by Benjamin-Loison** [comment]
On:

https://www.dhl.de/en/privatkunden/pakete-empfangen/verfolgen.html?piececode=XXXXXXXXXXXXX

Without `seleniumwireOptions`, then detected as usually, if with it:

<img width="2256" height="1424" alt="Image" src="https://github.com/user-attachments/assets/d7676649-0ed2-42da-8d14-b5f15652c3f5" />

**Comment by Benjamin-Loison** [comment]
Related to [Benjamin_Loison/curl_cffi/issues/3#issuecomment-7860749](https://codeberg.org/Benjamin_Loison/curl_cffi/issues/3#issuecomment-7860749).
